//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTicketCoral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coralticket
    {
        public int idTicket { get; set; }
        public string Usuario { get; set; }
        public string Operacion { get; set; }
        public string TipoConsulta { get; set; }
        public string Descripcion { get; set; }
        public byte[] Evidencia1 { get; set; }
        public byte[] Evidencia2 { get; set; }
        public byte[] Evidencia3 { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public string TIManager { get; set; }
    }
}
