//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTicketCoral.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketCoralEntities : DbContext
    {
        public TicketCoralEntities()
            : base("name=TicketCoralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coralticket> Coraltickets { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
        public virtual DbSet<EmpleadosBayer> EmpleadosBayers { get; set; }
        public virtual DbSet<EmpleadosPop> EmpleadosPops { get; set; }
        public virtual DbSet<ProductosBayer> ProductosBayers { get; set; }
        public virtual DbSet<ProductosPop> ProductosPops { get; set; }
        public virtual DbSet<VentasBayer> VentasBayers { get; set; }
        public virtual DbSet<VentasPop> VentasPops { get; set; }
    }
}
