//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTicketCoral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosBayer
    {
        public int Id { get; set; }
        public string NoEmpleado { get; set; }
        public string BadgeID { get; set; }
        public string Nombre { get; set; }
        public string Empresa { get; set; }
        public string Departamento { get; set; }
        public string Imagen { get; set; }
        public Nullable<bool> Subsidio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<bool> Auto { get; set; }
        public string Fecha { get; set; }
        public string Direccion { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> TipoSubsidio { get; set; }
        public string Gerencia { get; set; }
        public Nullable<int> DesbloqueoSub { get; set; }
        public Nullable<bool> SubAct { get; set; }
        public string IDSap { get; set; }
        public string TipoPago { get; set; }
        public Nullable<bool> EstadoEmp { get; set; }
    }
}
