//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTicketCoral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<float> Costo { get; set; }
        public string Proveedor { get; set; }
        public Nullable<float> CCompra { get; set; }
        public Nullable<int> Iva { get; set; }
        public Nullable<bool> SubPro { get; set; }
        public string Empresa { get; set; }
        public string codigo_cabys { get; set; }
    }
}
