//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTicketCoral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasBayer
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string NoTicket { get; set; }
        public string NoEmpleado { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<byte> Cantidad { get; set; }
        public string Operador { get; set; }
        public Nullable<double> Impuesto { get; set; }
        public Nullable<double> Subsidio { get; set; }
        public string Site { get; set; }
    }
}
